version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: entries
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"  # מפותח יציאה של MySQL בפורט 3308
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:                # <-- שורה חסרה במקור, מוסיפים את המפתח ports
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: entries
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data:
